<small class="bugs">
    <span><?= $block->escapeHtml(__('Help Us Keep Magento Healthy')) ?></span>
        <a href="http://www.magentocommerce.com/bug-tracking" target="_blank" title="<?= $block->escapeHtmlAttr(__('Report All Bugs')) ?>">
            <?= $block->escapeHtml(__('Report All Bugs')) ?>
        </a>
    <span style="display: inline-block;">
        <p>
            <img src="<?php echo $block->getViewFileUrl('images/footer/payoo.png'); ?>" alt="">
        </p>
    </span>
</small>
