<div class="container">
    <div class="row mt-5">
            <h1>Deals Of The </h1>
            <hr class="mt-3">
            <div class="row">
                <div class="col-12">
                    <div class="my-slick-carouseldealofday">
                            <div class="item" style="display: flex; align-items: center;">
                                <div>
                                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/dealofday.png'); ?>" alt="" style="max-width: 100%; height: auto; margin-right: 10px;" />
                                    <!-- <div>
                                        <h4 style="flex: 1;  overflow: hidden; text-overflow: ellipsis; margin: 0;">Sữa Dưỡng Phục Hồi Tái Tạo Da B5 Neogence 50ml</h4>
                                    </div> -->
                                </div>
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/dealofday.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/dealofday.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/dealofday.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/dealofday.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/dealofday.png'); ?>" alt="" />
                            </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Banners.png'); ?>" alt="imgpanelheader" />
                </div>
            </div>
     </div>
</div>