<div class="container">
    <div class="row mt-5">
            <h1>Your Recently Viewed Products</h1>
            <hr class="mt-3">
                <div class="row">
                    <div class="col-12">
                    <div class="my-slick-carouseldealofday">
                            <div class="item" >
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/RecentProduct1.png'); ?>" alt=""  />              
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/RecentProduct2.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/RecentProduct3.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/RecentProduct4.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/RecentProduct5.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/RecentProduct1.png'); ?>" alt="" />
                            </div>
                    </div>
                    </div>
                </div>
    </div>
</div>