
<div class="container">
    <div class="row mt-5">
        <h1><?php echo $block->getData('block_name'); ?></h1>
            <hr class="mt-3">
                <div class="row">
                    <div class="col-12">
                    <div class="my-slick-carouseldealofday">
                            <div class="item" >
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=""  />              
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product2.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product3.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product4.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product5.png'); ?>" alt="" />
                            </div>
                            <div class="item">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/dealofday.png'); ?>" alt="" />
                            </div>
                    </div>
                    </div>
                </div>
    </div>
</div>