<div class="container">
        <div class="row mt-5 ">
            <h1>Top Categories Of The Month</h1>
            <div class="mt-5">
                <div class="row">
                    <div class="col-4">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-5 p-3">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories1.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-7 contenttopcate p-4">
                                <h3>TV Televisions</h3>
                                <p>
                                    <p class="reviewtopcate">Smart TV </p>
                                    <p class="reviewtopcate">4K Ultra HD TVs</p>
                                    <p class="reviewtopcate">LED TVs</p>
                                    <p class="reviewtopcate">OLED TVs</p>
                                    <p class="reviewtopcate">Accessories</p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-5 p-3">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories2.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-7 contenttopcate p-4">
                                <h3>Personal Care</h3>
                                <p>
                                    <p class="reviewtopcate">Face mask</p>
                                    <p class="reviewtopcate">Face shield</p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="topcategories border">
                            <div class="row d-flex">
                            <div class="col-5 p-3">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories3.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-7 contenttopcate p-4">
                                <h3>Small Appliances</h3>
                                <p>
                                    <p class="reviewtopcate">Microwave oven</p>
                                    <p class="reviewtopcate">Air Fryer</p>
                                    <p class="reviewtopcate">Rice cooker</p>
                                    <p class="reviewtopcate">Kettle</p>
                                    <p class="reviewtopcate">Jar pot</p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-5 d-flex">
                    <div class="col-4">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-5 p-3">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories4.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-7 contenttopcate p-4">
                                <h3>Consumer Goods</h3>
                                <p>
                                    <p class="reviewtopcate">Washing and</p>
                                    <p class="reviewtopcate">Cleanser</p>
                                    <p class="reviewtopcate">Home care</p>
                                    <p class="reviewtopcate">Hygienic care</p>
                                    <p class="reviewtopcate">Insect treatment</p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-5 p-3">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories5.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-7 contenttopcate p-4">
                                <h3>Food & Drink</h3>
                                <p>
                                    <p class="reviewtopcate">Fruit</p>
                                    <p class="reviewtopcate">Confectionary</p>
                                    <p class="reviewtopcate">Beverage</p>
                                    <p class="reviewtopcate">Seasoning</p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-5 p-3">
                                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories6.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-7 contenttopcate p-4">
                                <h3>Dietary Supplement</h3>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>