<div class="container topcategoriescontainer">
        <div class="row mt-5 ">
            <h1><?=__('Top Categories Of The Month')?></h1>
            <div class="mt-5">
                <div class="row rowcategories">
                    <div class="col-4 itemcategories">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-6">
                                <img class="p-4" src="<?php echo $block->getViewFileUrl("Magento_Theme::images/topcategories1.png"); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-6">
                                <h3><?=__('TV Televisions')?></h3>
                                <p>
                                    <p class="reviewtopcate"><?=__('Smart TV ')?></p>
                                    <p class="reviewtopcate"><?=__('4K Ultra HD TVs')?></p>
                                    <p class="reviewtopcate"><?=__('LED TVs')?></p>
                                    <p class="reviewtopcate"><?=__('OLED TVs')?></p>
                                    <p class="reviewtopcate"><?=__('Accessories')?></p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 itemcategories">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-6">
                                <img class="p-4" src="<?php echo $block->getViewFileUrl("Magento_Theme::images/topcategories2.png"); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-6">
                                <h3><?=__('Personal Care')?></h3>
                                <p>
                                    <p class="reviewtopcate"><?=__('Face mask')?></p>
                                    <p class="reviewtopcate"><?=__('Face shield')?></p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 itemcategories">
                        <div class="topcategories border">
                            <div class="row d-flex">
                            <div class="col-6">
                                <img class="p-4" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories3.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-6">
                                <h3><?=__('Small Appliances')?></h3>
                                <p>
                                    <p class="reviewtopcate"><?=__('Microwave oven')?></p>
                                    <p class="reviewtopcate"><?=__('Air Fryer')?></p>
                                    <p class="reviewtopcate"><?=__('Rice cooker')?></p>
                                    <p class="reviewtopcate"><?=__('Kettle')?></p>
                                    <p class="reviewtopcate"><?=__('Jar pot')?></p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 itemcategories">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-6">
                                <img class="p-4" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories4.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-6">
                                <h3><?=__('Consumer Goods')?></h3>
                                <p>
                                    <p class="reviewtopcate"><?=__('Washing and')?></p>
                                    <p class="reviewtopcate"><?=__('Cleanser')?></p>
                                    <p class="reviewtopcate"><?=__('Home care')?></p>
                                    <p class="reviewtopcate"><?=__('Hygienic car')?>e</p>
                                    <p class="reviewtopcate"><?=__('Insect treatment')?></p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 itemcategories">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-6">
                                <img class="p-4" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories5.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-6">
                                <h3><?=__('Food & Drink')?></h3>
                                <p>
                                    <p class="reviewtopcate"><?=__('Fruit')?></p>
                                    <p class="reviewtopcate"><?=__('Confectionary')?></p>
                                    <p class="reviewtopcate"><?=__('Beverage')?></p>
                                    <p class="reviewtopcate"><?=__('Seasoning')?></p>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 itemcategories">
                        <div class="topcategories border">
                            <div class="row">
                            <div class="col-6">
                                <img class="p-4" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/topcategories6.png'); ?>" alt="imgtopcategories" />
                            </div>
                            <div class="col-6">
                                <h3><?=__('Dietary Supplement')?></h3>
                            </div>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
</div>