<footer>
    <div class="container pt-5">
        <div class="row mb-5 topfooter">
            <div class="col-3 itemfooter">
                <div id="quickLinksHeader" class="dropdownfooter">
                    <h4 class="headerfooter dropdown-content" ><?=__('QUICK LINKs')?></h4>
                    <svg class="imgdropdown" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                        <path d="M15 12.5L10 7.5L5 12.5" stroke="white" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </div>
                    <div class="mt-5" id="quickLinksList">
                        <p class="footertext">
                                <a class="footerlink" href=""><?= __("Terms & Conditions") ?></a>
                        </p> 
                        <p class="footertext">
                                <a class="footerlink" href=""><?=__("Privacy Policies")?></a>
                        </p>  
                        <p class="footertext">
                                <a class="footerlink" href=""><?=__("Delivery - Return - Warranty")?></a>
                        </p>  
                        <p class="footertext">
                                <a class="footerlink" href=""><?=__('Payment Methods')?></a>
                        </p>  
                        <p class="footertext">
                                <a class="footerlink" href=""><?=__('Loyalty Program')?></a>
                        </p>  
                    </div>
            </div>

            <div class="col-3 itemfooter">
                    <div id="quickLinksHeader2" class="dropdownfooter">
                        <h4 class="headerfooter dropdown-content"><?=__('COMPANY')?></h4>
                        <svg class="imgdropdown" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                            <path d="M15 12.5L10 7.5L5 12.5" stroke="white" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </div>
                    <div class="mt-5" id="quickLinksList2">
                        <p class="footertext">
                            <a class="footerlink" href=""><?=__('About us')?></a>
                        </p> 
                        <p class="footertext">
                            <a class="footerlink" href=""><?=__('FAQs')?></a>
                        </p> 

                        <div class="mt-2">
                            <img src="<?php echo $block->getViewFileUrl('images/nganhang.png'); ?>" alt="">
                        </div>
                    </div>
                    
            </div>
            <div class="col-3 itemfooter">
                 <div id="quickLinksHeader3" class="dropdownfooter">
                    <h4 class="headerfooter"><?=__('Follow us')?></h4>
                    <svg class="imgdropdown" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                            <path d="M15 12.5L10 7.5L5 12.5" stroke="white" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </div>
                
                <div class="mt-5" id="quickLinksList3">
                    <h4 class="headerfooter"><?=__('Our Mobile Apps')?></h4>
                    <div>
                        <img src="<?php echo $block->getViewFileUrl('images/appstore.png'); ?>" alt="">
                    </div>
                    <div>
                        <img src="<?php echo $block->getViewFileUrl('images/googleplay.png'); ?>" alt="">
                    </div>
                </div>
                   
            </div>
            <div class="col-3 itemfooter itemfooteripad">
                <div  class="dropdownfooter">
                    <h4 class="headerfooter"><?=__('CÔNG TY TNHH ĐIỆN TỬ SHARP VIỆT NAM')?></h4>
                </div>
                <div class="mt-5 ssss">
                    <p class="footerp">

                    <?=__(' Địa chỉ:')?>
                        T5-B03.07 & T5-B03.09, Lầu 3 Masteri Thảo Điền
                        159 Xa Lộ Hà Nội, Phường Thảo Điền, T.P Thủ Đức, T.P Hồ Chí Minh, Việt Nam
                       
                    </p>
                    <p class="footerp">
                    <?=__('   Email:')?>
                        cskh@cocorolife.vn
                    </p>
                    <p class="footerp">
                    <?=__('   MST: ')?>
                    0308159258 Do Sở kế hoạch Đầu tư TP.HCM cấp ngày 13/3/2009
                    </p>
                    <p>
                        <img src="<?php echo $block->getViewFileUrl('images/thongbao.png'); ?>" alt="">
                    </p>
                </div>  
            </div>
        </div>
        <hr>
        <div class="row coppyright">
            <div class="col-6 footerdesgin">
                <p class="footerlink"><?=__ ('© 2022 Cocoro Life. All Rights Reserved'); ?> </p>
            </div>
            <div class="col-6 coppyrightend footerdesgin">
                <p class="footerp"><?=__ ('Our Payment Provider') ?></p>
                <span style="display: inline-block;">
                    <p>
                        <img src="<?php echo $block->getViewFileUrl('images/payoo.png'); ?>" alt="">
                    </p>
                </span>
            </div>
        </div>
    </div>
</footer>
