<footer style="background-color: #DA6897;">
    <div class="container pt-5">
        <div class="row mb-5">
            <div class="col-3">
                <h4 class="headerfooter">QUICK LINKs</h4>
                <div class="mt-5">
                   <p class="footertext">
                        <a class="footerlink" href="">Terms & Conditions</a>
                   </p> 
                   <p class="footertext">
                        <a class="footerlink" href="">Privacy Policies</a>
                   </p>  
                   <p class="footertext">
                        <a class="footerlink" href="">Delivery - Return - Warranty</a>
                   </p>  
                   <p class="footertext">
                        <a class="footerlink" href="">Payment Methods</a>
                   </p>  
                   <p class="footertext">
                        <a class="footerlink" href="">Loyalty Program</a>
                   </p>  
                </div>
            </div>
            <div class="col-3">
                <h4 class="headerfooter">COMPANY</h4>
                <div class="mt-5">
                    <p class="footertext">
                        <a class="footerlink" href="">About us</a>
                    </p> 
                    <p class="footertext">
                        <a class="footerlink" href="">FAQs</a>
                    </p> 
                </div>
                <div class="mt-2">
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/nganhang.png'); ?>" alt="">
                </div>
            </div>
            <div class="col-3">
                <h4 class="headerfooter">Follow us</h4>
                <h4 class="headerfooter">Our Mobile Apps</h4>
                <div>
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/appstore.png'); ?>" alt="">
                </div>
                <div>
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/googleplay.png'); ?>" alt="">
                </div>
            </div>
            <div class="col-3">
                <h4 class="headerfooter">CÔNG TY TNHH ĐIỆN TỬ SHARP VIỆT NAM</h4>
                <p class="footerlink">
                    Địa chỉ: T5-B03.07 & T5-B03.09, Lầu 3 Masteri Thảo Điền
                    159 Xa Lộ Hà Nội, Phường Thảo Điền, T.P Thủ Đức, T.P Hồ Chí Minh, Việt Nam
                </p>
                <p class="footerlink">
                    Email: cskh@cocorolife.vn
                </p>
                <p class="footerlink">
                    MST: 0308159258 Do Sở kế hoạch Đầu tư TP.HCM cấp ngày 13/3/2009
                </p>
                <p>
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/thongbao.png'); ?>" alt="">
                </p>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-6">
                <p class="footerlink">© 2022 Cocoro Life. All Rights Reserved</p>
            </div>
            <div class="col-6 text-end">
                <p>Our Payment Provider</p>
                <span style="display: inline-block;">
                    <p>
                        <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/payoo.png'); ?>" alt="">
                    </p>
                </span>
            </div>
        </div>
    </div>
</footer>
