<div class="">
    <div class="row">
        <div class="col-1" style="background-color: #040F25;">

        </div>
        <div class="col-10 d-flex">
            <image style="width: 100%; margin: 0;" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/banner1.png'); ?>"" alt="imgpanelheader"/>
        </div>
        <div class="col-1" style="background-color: #072758;">
        </div>
    </div>
</div>


